config/routes.rb
PatientCareApp::Application.routes.draw do

  root 'home#index'

  resources :survey_types
  resources :survey_steps do
    resources :survey_step_responses, as: 'response'
  end

  resources :users do
    post "duplicate" => "users#duplicate", on: :collection
    get "lookup" => "users#new_lookup", on: :collection
    post "lookup" => "users#lookup", on: :collection
  end

  get 'thank_you' => 'home#thank_you'

end

app/models/survey_step.rb
class SurveyStep < ActiveRecord::Base
  belongs_to :survey_type
  belongs_to :next_step, class_name: 'SurveyStep'
  # TODO: Look for a more concise way to specify this foreign key.
  has_one :previous_step, class_name: 'SurveyStep', foreign_key: :next_step_id
  has_many :questions, -> { order "sequence ASC" }, class_name: 'SurveyQuestion'

  validates :name, presence: true
  validates :name, :custom_action, length: { maximum: 255 }
  validates :intro, length: { maximum: 1000 }

  # Returns an all lowercase version of the name with spaces replaced with dashes.
  def slug
    self.name.downcase.dasherize.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
  end

end

app/controllers/survey_steps_controller.rb
class SurveyStepsController < ApplicationController

  def show
    step_id = params[:id]
    @step = SurveyStep.find(step_id)

    if !@step
      # TODO: Add a flash message.
      redirect_to root_path
      return
    end

    render @step.custom_view if @step.custom_view
  end

end

app/views/survey_steps/create_user.html.erb
<!-- TODO: Figure out how to handle the case when the @user has already been saved. -->
<%= form_tag(survey_step_path, { id: "#{@step.slug}-form", class: 'survey-step' }) do %>
  <div class="title">Please answer the following:</div>

  <div class="question name">
    <%= label_tag(:full_name, 'What is your first and last name?', class: :required) %>
    <div class="response">
      <%= text_field_tag(:first_name, '', placeholder: 'First Name') %>
      <%= text_field_tag(:last_name, '', placeholder: 'Last Name') %>
    </div>
  </div>

  <div class="question birth-date">
    <%= label_tag(:birth_date, 'What is your date of birth?', class: :required) %>
    <div class="response">
      <%= date_field_tag(:birth_date, nil) %>
      <!-- TODO: Find a better date field. -->
    </div>
  </div>

  <div class="question gender">
    <%= label_tag(:gender, 'What is your gender?') %>
    <div class="response">
      <%= select_tag(:gender, options_for_select([ ['Select one...', nil],
                                                   ['Male',:male],
                                                   ['Female',:female],
                                                   ['Not specified',:other]
                                                 ], nil)) %>
    </div>
    <div class="followup">
      <%= label_tag(:gender_other, 'If not specified:') %>
      <div class="response">
        <%= text_field_tag(:gender_other, '', placeholder: 'Please write in here') %>
      </div>
    </div>
  </div>

  <!-- TODO: Figure out why ethnicity and ethnicity other are not saving. -->
  <div class="question race">
    <%= label_tag(:ethnicity, 'What is your race/ethnicity?') %>
    <div class="response">
      <%= select_tag(:ethnicity, options_for_select([ ['Select one...', nil],
                                                      ['American Indian or Alaska Native',:american_indian],
                                                      ['Asian',:asian],
                                                      ['Hispanic, Latino, or Spanish Origin',:hispanic],
                                                      ['Black or African American',:african_americas],
                                                      ['Native Hawaiian or Other Pacific Islander',:pacific_islander],
                                                      ['White',:white],
                                                      ['Other, please specify.',:other]
                                                    ], nil)) %>
    </div>
    <div class="followup">
      <%= label_tag(:ethnicity_other, 'If other:') %>
      <div class="response">
        <%= text_field_tag(:ethnicity_other, '', placeholder: 'Please write in here') %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= hidden_field_tag(:next_action, '', class: :action) %>

    <%= link_to("Cancel", '#', onClick: 'submitForm("cancel")', class: :cancel) %>
    <%= link_to("Next", '#', onClick: 'submitForm("submit")', class: :next) %>
  </div>

<% end %>


<script>
  var submitForm = function(action) {
    var options = {};
    if (action == 'submit') {
      options = {
        validate: [ {
          selector: 'input[name=first_name]',
          required: true
        }, {
          selector: 'input[name=last_name]',
          required: true
        }, {
          selector: 'input[name=birth_date]',
          required: true,
          dataType: 'date'
        } ]
      };
    }

    patientCare.submitForm("create-user-form", action, options);
  };
</script>

app/views/survey_steps/show.html.erb
<%= form_tag(survey_step_path, { id: "#{@step.slug}-form", class: 'survey-step' })do %>
  <div class="title"><%= @step.intro %></div>

  <div class="questions">
    <% @step.questions.each do |question| %>
      <%= render(partial: 'survey_questions/question', locals: { question: question }) %>
    <% end %>
  </div>

  <div class="actions">
    <%= hidden_field_tag(:step, '', class: :action) %>

    <%= link_to("Cancel", '#', onClick: 'submitForm("cancel")', class: :cancel) %>
    <%= link_to("Back", '#', onClick: 'submitForm("back")', class: :back) %>
    <%= link_to("Next", '#', onClick: 'submitForm("submit")', class: :next) %>
  </div>
<% end %>

<script>
  var submitForm = function(action) {
    patientCare.submitForm("survey-step-form", action, {});
  };
</script>