config/routes.rb
PatientCareApp::Application.routes.draw do

  root 'home#index'

  resources :survey_types
  resources :survey_steps do
    resources :survey_step_responses, as: 'response'
  end

  resources :users do
    post "duplicate" => "users#duplicate", on: :collection
    get "lookup" => "users#new_lookup", on: :collection
    post "lookup" => "users#lookup", on: :collection
  end

  get 'thank_you' => 'home#thank_you'

end

app/models/user.rb
class User < ActiveRecord::Base
  lookup_for :gender
  lookup_for :ethnicity

  validates :first_name, :last_name, :birth_date, presence: true
  validates :first_name, :last_name, length: { maximum: 255 }
  validates :birth_date, presence: true, date: { on_or_after: :birth_date_first, on_or_before: :birth_date_last }
  # TODO: Add validation for other gender and other race responses.

  def self.birth_date_first
    118.years.ago
  end

  def self.birth_date_last
    0.days.ago
  end

  def duplicates
    dup_attrs = {
      first_name: self.first_name,
      last_name: self.last_name,
      birth_date: self.birth_date
    };
    User.where(dup_attrs)
  end

  def duplicate?
    !duplicates.empty?
  end

  def last_update
    last_submission = SurveyResponse.where(user: self).order(updated_at: :desc).limit(1)
    if !last_submission.empty?
      return last_submission.first.updated_at
    else
      return self.created_at
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = current_survey_response.user || User.new
  end

  def create
    step = SurveyStep.find_by_name(:create_user)
    if !step
      logger.error("Unable to find create_user step.")

      flash.now[:alert] = "Configuration error detected."
      redirect_to root_path
      return
    end

    process_step_response(step, params[:next_action]) do
      @user = User.new
      return if !update_user(user_params)

      survey_response = current_survey_response
      survey_response.user = @user
      survey_response.save!
    end
  end

  def update
    step = SurveyStep.find_by_name(:create_user)
    if !step
      logger.error("Unable to find create_user step.")

      flash.now[:alert] = "Configuration error detected."
      redirect_to root_path
      return
    end

    process_step_response(step, params[:next_action]) do
      @user = User.new
      return if !update_user(user_params)

      survey_response = current_survey_response
      survey_response.user = @user
      survey_response.save!
    end
  end

  def new_lookup
    @user = current_survey_response.user || User.new
  end

  def lookup
    step = SurveyStep.find_by_name(:lookup_user)
    if !step
      logger.error("Unable to find lookup_user step.")

      flash.now[:alert] = "Configuration error detected."
      redirect_to root_path
      return
    end

    process_step_response(step, params[:next_action]) do
      if !user_params[:first_name] ||
          !user_params[:last_name] ||
          !user_params[:birth_date]
        flash.now[:alert] = "Missing required fields."
        @user = User.new(user_params)
        render :new_lookup
        return
      end

      # Note: Using lower here prevents us from using our indexes.
      users = User.where("lower(first_name) = lower(?) AND lower(last_name) = lower(?) AND birth_date = ?",
                         user_params[:first_name],
                         user_params[:last_name],
                         user_params[:birth_date])

      if users.empty?
        flash.now[:notice] = "No matching user found."
        @user = User.new(user_params)
        render :new_lookup
        return
      end

      @user = users.first
      survey_response = current_survey_response
      survey_response.user = @user
      survey_response.save!

      if users.size > 1
        render :duplicate_check
        return
      end
    end
  end

  def duplicate
    if new_patient?
      step_key = :duplicate_user
    else
      step_key = :multiple_users
    end
    step = SurveyStep.find_by_name(step_key)
    if !step
      logger.warn("Unable to find #{step_key} step.")

      flash.now[:alert] = "Configuration error detected."
      redirect_to root_path
      return
    end

    process_step_response(step, params[:next_action]) do
      if !duplicate_check_params[:duplicate_user_id].blank?
        return if !lookup_duplicate(duplicate_check_params[:duplicate_user_id])
      else
        if new_patient?
          user_attrs = session[:pending_user_attrs]
          user_attrs.delete('id')

          @user = User.new
          return if !update_user(user_attrs, check_dup: false)
        else
          flash.now[:alert] = "A previous account is required for returning patients."
          redirect_to lookup_users_path
          return
        end
      end
      session[:pending_user_attrs] = nil

      survey_response = current_survey_response
      survey_response.user = @user
      survey_response.save!
    end
  end

private

  def user_params
    begin
      params.require(:user)
        .permit(:first_name,
                :last_name,
                :birth_date,
                :gender,
                :gender_other,
                :ethnicity,
                :ethnicity_other)
    rescue ActionController::ParameterMissing => e
      logger.info "Failed to parse user params from #{params.inspect}"
      {}
    end
  end

  def duplicate_check_params
    begin
      params
        .permit(:duplicate_user_id)
    rescue ActionController::ParameterMissing => e
      logger.info "Failed to parse duplicate check params from #{params.inspect}"
      {}
    end
  end

  def lookup_duplicate(user_id)
    @user = User.find(user_id)

    if !@user
      redirect_to new_user_path
      return false
    end

    return true
  end

  def update_user(user_attrs, opts = {})
    logger.debug "Creating new User with attributes: #{user_attrs.inspect()}"

    opts = {check_dup: true}.merge(opts)

    if user_attrs.blank?
      redirect_to new_user_path
      return false
    end

    @user.assign_attributes(user_attrs)

    # Make sure this is a valid request before entering the duplicate workflow.
    if !@user.valid?
      render :new
      return false
    end

    # Check if this is a duplicate user.
    if opts[:check_dup] && @user.duplicate?
      session[:pending_user_attrs] = @user.attributes
      render :duplicate_check
      return false
    end

    if !@user.save
      redirect_to new_user_path
      return false
    end

    logger.debug("Succesfully created new User.")
    return true
  end

end

app/views/users/duplicate_check.html.erb
<div id="duplicate-user-check">
  <div class="title">We found recods with similar personal information. Is one of the following an existing record for you?</div>

  <!-- Note: This is outside of the form because this data will need to be transformed before being submitted to the server. -->
  <div class="users">
    <% for user in @user.duplicates %>
      <div class="user">
        <div class="selector">
          <%= check_box_tag "user_#{user.id}", 1, false, data: { 'user-id' => user.id } %>
        </div>
        <%= label_tag "user_#{user.id}", class: 'user-details' do %>
          <div class="full-name attr">
            <span class="first-name"><%= user.first_name %></span>
            <span class="last-name"><%= user.last_name %></span>
          </div>
          <div class="birth-date attr">
            <div class="label">Birth Date:</div>
            <div class="value"><%= user.birth_date %></div>
          </div>
          <div class="gender attr">
            <div class="label">Gender:</div>
            <div class="value"><%= user.gender.try(:titleize) %></div>
          </div>
          <div class="ethnicity attr">
            <div class="label">Ethnicity:</div>
            <div class="value"><%= user.ethnicity.try(:titleize) %></div>
          </div>
          <div class="last-update attr">
            <div class="label">Last Use:</div>
            <div class="value"><%= user.last_update %></div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= form_tag(duplicate_users_path, id: 'duplicate-user-form') do %>
    <%= hidden_field_tag :duplicate_user_id %>
    <%= hidden_field_tag(:next_action, '', class: :action) %>

    <div class="actions">
      <%= link_to("Cancel", '#', onClick: 'submitForm("cancel")', class: :cancel) %>
      <%= link_to("No, None are me.", '#', onClick: 'submitForm("submit")', class: :next) %>
    </div>
  <% end %>

</div>

<script>
  $(document).ready(function() {
    var NO_DUP_FOUND_LABEL = "No, None are me.";
    var DUP_FOUND_LABEL = "Yes, This is me.";

    var $form = $('#duplicate-user-check form');
    var $userField = $form.find('#duplicate_user_id');
    var $submitButton = $form.find('a.next');

    setupPresenceBasedButtonLabelToggle($userField, $submitButton, 
                                        DUP_FOUND_LABEL, NO_DUP_FOUND_LABEL);

    var userCheckboxSelector = '#duplicate-user-check .users .user input[type=checkbox]';
    setupUserSelectionHandlers(userCheckboxSelector, 'userId', $userField);
  });

  var submitForm = function(action) {
    patientCare.submitForm("duplicate-user-form", action, {});
  };
</script>

app/views/users/new.html.erb
<!-- TODO: Figure out how to handle the case when the @user has already been saved. -->
<%= form_for(@user, html: { id: 'new-user', class: 'survey-step' }) do |f| %>
  <div class="title">Please answer the following:</div>

  <div class="question name">
    <%= f.label(:full_name, 'What is your first and last name?', class: :required) %>
    <div class="response">
      <%= f.text_field(:first_name, placeholder: 'First Name') %>
      <%= f.text_field(:last_name, placeholder: 'Last Name') %>
    </div>
  </div>

  <div class="question birth-date">
    <%= f.label(:birth_date, 'What is your date of birth?', class: :required) %>
    <div class="response">
      <%= f.date_field(:birth_date) %>
      <!-- TODO: Find a better date field. -->
    </div>
  </div>

  <div class="question gender">
    <%= f.label(:gender, 'What is your gender?') %>
    <div class="response">
      <%= f.select(:gender, [
                     ['Select one...', nil],
                     ['Male',:male],
                     ['Female',:female],
                     ['Not specified',:other]
                     ]) %>
    </div>
    <div class="followup">
      <%= f.label(:gender_other, 'If not specified:') %>
      <div class="response">
        <%= f.text_field(:gender_other, placeholder: 'Please write in here') %>
      </div>
    </div>
  </div>

  <!-- TODO: Figure out why ethnicity and ethnicity other are not saving. -->
  <div class="question race">
    <%= f.label(:ethnicity, 'What is your race/ethnicity?') %>
    <div class="response">
      <%= f.select(:ethnicity, [
                     ['Select one...', nil],
                     ['American Indian or Alaska Native',:american_indian],
                     ['Asian',:asian],
                     ['Hispanic, Latino, or Spanish Origin',:hispanic],
                     ['Black or African American',:african_americas],
                     ['Native Hawaiian or Other Pacific Islander',:pacific_islander],
                     ['White',:white],
                     ['Other, please specify.',:other]
                   ]) %>
    </div>
    <div class="followup">
      <%= f.label(:ethnicity_other, 'If other:') %>
      <div class="response">
        <%= f.text_field(:ethnicity_other, placeholder: 'Please write in here') %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= hidden_field_tag(:next_action, '', class: :action) %>

    <%= link_to("Cancel", '#', onClick: 'submitForm("cancel")', class: :cancel) %>
    <%= link_to("Next", '#', onClick: 'submitForm("submit")', class: :next) %>
  </div>

<% end %>


<script>
  var submitForm = function(action) {
    var options = {};
    if (action == 'submit') {
      options = {
        validate: [ {
          selector: 'input#user_first_name',
          required: true
        }, {
          selector: 'input#user_last_name',
          required: true
        }, {
          selector: 'input#user_birth_date',
          required: true,
          dataType: 'date'
        } ]
      };
    }

    patientCare.submitForm("new-user", action, options);
  };
</script>

app/views/users/new_lookup.html.erb
<!-- TODO: Figure out how to handle the case when the @user has already been saved. -->
<%= form_for(@user, 
             url: lookup_users_path,
             method: 'POST',
             html: { id: 'lookup-user', class: 'survey-step' }) do |f| %>
  <div class="title">Please answer the following:</div>

  <div class="question name">
    <%= f.label(:full_name, 'What is your first and last name?', class: :required) %>
    <div class="response">
      <%= f.text_field(:first_name, placeholder: 'First Name') %>
      <%= f.text_field(:last_name, placeholder: 'Last Name') %>
    </div>
  </div>

  <div class="question birth-date">
    <%= f.label(:birth_date, 'What is your date of birth?', class: :required) %>
    <div class="response">
      <%= f.date_field(:birth_date) %>
      <!-- TODO: Find a better date field. -->
    </div>
  </div>

  <div class="actions">
    <%= hidden_field_tag(:next_action, '', class: :action) %>

    <%= link_to("Cancel", '#', onClick: 'submitForm("cancel")', class: :cancel) %>
    <%= link_to("Next", '#', onClick: 'submitForm("submit")', class: :next) %>
  </div>

<% end %>


<script>
  var submitForm = function(action) {
    var options = {};
    if (action == 'submit') {
      options = {
        validate: [ {
          selector: 'input#user_first_name',
          required: true
        }, {
          selector: 'input#userlast_name',
          required: true
        }, {
          selector: 'input#user_birth_date',
          required: true,
          dataType: 'date'
        } ]
      };
    }

    patientCare.submitForm("lookup-user", action, options);
  };
</script>