config/routes.rb
PatientCareApp::Application.routes.draw do

  root 'home#index'

  resources :survey_types
  resources :survey_steps do
    resources :survey_step_responses, as: 'response'
  end

  resources :users do
    post "duplicate" => "users#duplicate", on: :collection
    get "lookup" => "users#new_lookup", on: :collection
    post "lookup" => "users#lookup", on: :collection
  end

  get 'thank_you' => 'home#thank_you'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_survey_response, only: [:index, :thank_you]

  def index
    @new_patient = SurveyType.find_by_survey_type(:new_patient)
    @returning_patient = SurveyType.find_by_survey_type(:returning_patient)
  end
end

app/views/home/index.html.erb
<div id="home">
  <!-- NOTE: The div tags here MUST but up against the link_to tag to prevent additional linking whitespace from rendering. -->
  <%= link_to survey_type_path(@new_patient) do %><div class="btn new">
      <div class="centerer"></div>
      <div class="label">New<br/>Patient</div>
    </div><% end %>

  <%= link_to @returning_patient do %><div class="btn returning">
      <div class="centerer"></div>
      <div class="label">Returning<br/>Patient</div>
    </div><% end %>
</div>

app/views/home/thank_you.html.erb
<div id="thank-you">
  <div class="centerer"></div>
  <div class="msg">
    <%= image_tag asset_path("thankYou/thankYou.png"); %>
    <div class="intro">Your response has been recorded.</div>
  </div>
</div>

<!-- Return to home page after 10 seconds. -->
<script>
  $(document).ready(function() {
    window.patientCare.autoRedirect('<%= root_path %>', 10000);
  });
</script>